# Generated by Django 4.1.7 on 2023-04-18 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_miblog_delete_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miblog',
            name='imagenblog',
        ),
    ]
