# Generated by Django 4.1.7 on 2023-04-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_alter_miblog_imagenblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miblog',
            name='cuerpo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
