# Generated by Django 4.1.7 on 2023-04-20 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppCoder', '0008_miblog_fecha_miblog_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='micomentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_coment', models.DateTimeField(auto_now=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('blog_coment', models.TextField()),
                ('usuario_coment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiantes',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
